"""add role to users

Revision ID: 2fecd946cc6d
Revises: 31f74701df43
Create Date: 2026-07-20 22:50:39.336525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fecd946cc6d'
down_revision: Union[str, Sequence[str], None] = '31f74701df43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=16), nullable=False))
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), nullable=False))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
