"""add message metrics (tokens/duration/thinking_count/reasoning)

Revision ID: 5ae8b68410df
Revises: 2fecd946cc6d
Create Date: 2026-07-21 21:22:26.961269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ae8b68410df'
down_revision: Union[str, Sequence[str], None] = '2fecd946cc6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('duration_ms', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('thinking_count', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('reasoning_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'reasoning_text')
    op.drop_column('messages', 'thinking_count')
    op.drop_column('messages', 'duration_ms')
    op.drop_column('messages', 'total_tokens')
    op.drop_column('messages', 'completion_tokens')
    op.drop_column('messages', 'prompt_tokens')
    # ### end Alembic commands ###
